### ISSUE TITLE
Refazer a concepção do projeto, as referências e a aplicação ideal.

### ISSUE THREAD

**Issue by karolinemc** [super-poderosas/caixadememorias#6]
Ideia (se possível) completa do jogo ou aplicação a ser desenvolvido:

- [x]  Enredo ou roteiro.

- [x]  Mecânica de funcionamento.

- [x]  Referências (livros, jogos, etc.).**

**Comment by karolinemc** [comment]
Publiquei no arquivo README.md a premissa e as referências.

**Comment by GeovanaF6** [comment]
Publiquei no arquivo README.md a aplicação ideal do novo jogo que estamos desenvolvendo.
